### ISSUE TITLE
API Extractor check is sensible to library version

### ISSUE THREAD

**Issue by nicfix** [RevenueCat/purchases-js#118]
# Context
When running the `npm run extract-api` command we generate the `api-report/purchases-js-api.json`.
This file is then checked in circle-ci for differences using `git diff`.

# Problem
However the file includes the version of the library used to generate it so we need to hardcore it to the version used so far, which is inconvenient.

We need to find a way to check for differences differently or to ignore the tool version from the check.

# Example
An example here:
https://app.circleci.com/pipelines/github/RevenueCat/purchases-js/236/workflows/9db43040-0ab2-4dc5-8bd4-7900e9563de0/jobs/526?invite=true#step-118-265_29

**Comment by tonidero** [comment]
I believe we could potentially just diff the `.md` file, which doesn't contain the version. That way we protect ourselves against this. Thanks for reporting it!
