### ISSUE TITLE
One-time purchases

### ISSUE THREAD

**Issue by Kebechet** [RevenueCat/purchases-js#132]
In your [documentation](https://www.revenuecat.com/docs/web/revenuecat-billing#:~:text=Only%20subscriptions%20are%20currently%20supported%2C%20no%20one%2Dtime%20purchases) I read that currently you dont support one-time payments.

Is this still true ? And if so, is there a plan to implement it in near future ?

Thanks

**Comment by jefago** [comment]
This is still true. We will work on this but right now this is only planned for later this year.

**Comment by Kebechet** [comment]
Thank you for the info
