### ISSUE TITLE
New Feature setEmail

### ISSUE THREAD

**Issue by teury** [RevenueCat/purchases-js#141]
For projects where users authenticate and verify their email, it would be safer to allow the assignment of email through a "setEmail" function. This prevents users from mistyping their email addresses and avoids all the potential issues that could arise in the future (not seeing invoices, being unable to cancel subscriptions).

**Comment by tonidero** [comment]
Hi @teury,

Sorry for the late response. You can pass a verified email in the `purchase` method as part of the [PurchaseParams](https://revenuecat.github.io/purchases-js-docs/0.4.0/interfaces/PurchaseParams.html) object. If you pass it that way, we won't ask the user to input it again.

We do however require the user to verify the email by clicking on the button on the first email sent to continue receiving invoices/emails. This is to make sure the email is valid and doesn't fall into spam traps.

Let us know if that answers your question!

**Comment by tonidero** [comment]
Hi @teury, Going to tentatively close this but please let us know if you have further questions!
