### ISSUE TITLE
i18n

### ISSUE THREAD

**Issue by gezquinndesign** [RevenueCat/purchases-js#181]
Hello,

Is there any way to translate the strings on the checkout? I can force some translation via the browser language but it only updates the Stripe components. As illustrated below, I would expect to see no English (other than the company name), just Japanese.  I don't think there's currently a way to change this.

<img width="1376" alt="Screenshot 2024-09-13 at 13 27 36" src="https://github.com/user-attachments/assets/817febc0-d8d6-4bdc-a913-485d58603b54">

**Comment by nicfix** [comment]
Hi @gezquinndesign, thanks for trying `purchases-js`!

At the moment there's no support for localisation, we do not have a concrete ETA but it's in our roadmap.

**Comment by gezquinndesign** [comment]
OK, no problem.  Just thought I'd check.  The package is just about OK to use in production but I'd say this, plus #182 and a way to purchase `non-subscription purchases` are the things we'd like to see most.  Thanks for responding.  Shall I open another ticket for the non-subscription purchases?

**Comment by nicfix** [comment]
Non subscription purchases are already in our roadmap for this year. Regarding [i18n](https://github.com/RevenueCat/purchases-js/issues/182) and upgrades I'll make sure they reach our backlog.

Thanks again for looking into `purchases-js` and suggesting these improvements. 

We are working as fast as possible to ship new features, but there are some dependencies we need to follow that drive a bit our roadmap.

**Comment by gezquinndesign** [comment]
Awesome! I saw the updates and was going to check it out soon! Thanks for letting me know. If we wanted to request support for an additional language, is that possible?
