### ISSUE TITLE
Manage subscription link

### ISSUE THREAD

**Issue by gezquinndesign** [RevenueCat/purchases-js#183]
I notice that in the email that contains the invoice, there is a link to the customer portal so that the user can manage their subscription.  I'm just wondering if a similar link can be added to the entitlement info returned by the SDK?

**Comment by antoniobg** [comment]
Hi @gezquinndesign, this should be working now. Let us know if you find any issues.

**Comment by gezquinndesign** [comment]
Nice, tested it out and it works perfectly, thank you!  The only thing I'd mention is that I was expecting to see it specifically on the `PurchasesEntitlementInfo` rather than the `CustomerInfo` but I guess there's some reasoning in why it was added where it was added...

**Comment by nicfix** [comment]
Hi @gezquinndesign, 
happy to hear it works well!

And yes, the current solution might feel a bit cumbersome. We are working on changing this structure for the future. We decided to follow this approach to keep similarity with our other SDKs.

We will revisit this decision in the future, but we need to find a good solution that works both for `purchases-js` and the other SDKs before proceeding.

I'll close this issue to keep the issues tab clean.
Thanks for all your comments and testing, really appreciated!

**Comment by gezquinndesign** [comment]
Cool, I thought that would be the reason. Thanks for getting this feature out so quickly, much appreciated.
