### ISSUE TITLE
Ready to use

### ISSUE THREAD

**Issue by SilverLinings89** [RevenueCat/purchases-js#97]
Hi everyone,

I was just wondering if this is ready to use. We currently use a lambda function in the backend and query the API from there to get the subscriber state. Can we use this library instead?

I'm asking because on the one hand this repo is not referenced from the original docs but also doesn't contain a flag that it isn't ready for use yet.

**Comment by jefago** [comment]
Tomorrow :) some parts are still waiting to be shipped

**Comment by SilverLinings89** [comment]
Great to hear :) I had been wondering where to get the rcb_ key after installing the package. Looks really good and I think this will be a great step!
